# .github/workflows/rust.yml
 name: RusTor

 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout repository
       uses: dtolnay/rust-toolchain@stable
       with:
         toolchain: stable

     - name: Set up Rust
       uses: actions/setup-rust@v1
       with:
         rust-version: stable

     - name: Install Clippy & Rustfmt
       run: rustup component add clippy rustfmt

     - name: Check formatting
       run: cargo fmt --check

     - name: Run Clippy (lint)
       run: cargo clippy --all-targets --all-features -- -D warnings

     - name: Build
       run: cargo build --verbose

     - name: Check for main binary
       run: |
         if [ ! -f target/debug/rustor ]; then
           echo "Main binary not found! Make sure you have a main.rs with #[tokio::main]."
           exit 1
         fi

     - name: Run Tests (if any)
       run: cargo test --verbose || echo "No tests found."
 
